version: '3.5'

services:

  mysql:
    image: mysql:5.7
    container_name: zabbix_db
    environment:
      - MYSQL_ROOT_PASSWORD=zabbixpasswd
      - MYSQL_DATABASE=zabbixdb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - stack_zabbix


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elk_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - stack_zabbix

  zabbixsr:
    image: zabbix/zabbix-server-mysql:centos-3.4.11
    container_name: zabbix_server
    restart: always
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=zabbixpasswd
      - MYSQL_DATABASE=zabbixdb
      - ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200
      - ZBX_HISTORYSTORAGETYPES=uint,dbl,str,log,text
      - ZBX_TIMEOUT=30
    ports:
      - 10050:10050
      - 10051:10051
    depends_on:
      - "mysql"
      - "elasticsearch"
    networks:
      - stack_zabbix

  webapp:
    image: zabbix/zabbix-web-nginx-mysql:centos-3.4.11
    container_name: zabbix_web
    restart: always
    environment:
      - ZBX_SERVER_HOST=zabbixsr
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=zabbixpasswd
      - MYSQL_DATABASE=zabbixdb
      - PHP_TZ=America/Sao_Paulo
      - ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200
      - ZBX_HISTORYSTORAGETYPES="['uint','dbl','str','log','text']"
    ports:
      - 8080:80
    depends_on:
      - "mysql"
      - "elasticsearch"
    networks:
      - stack_zabbix

volumes:
  elk_data:
    driver: local
  
  mysql_data:
    driver: local

networks:
  stack_zabbix: